const data = [{
    "id": 1,
    "country": "Colombia",
    "city": "Itagüí"
}, {
    "id": 2,
    "country": "Mexico",
    "city": "La Palma"
}, {
    "id": 3,
    "country": "China",
    "city": "Jicun"
}, {
    "id": 4,
    "country": "Norway",
    "city": "Bergen"
}, {
    "id": 5,
    "country": "Canada",
    "city": "Sainte-Thérèse"
}, {
    "id": 6,
    "country": "Philippines",
    "city": "Matinao"
}, {
    "id": 7,
    "country": "China",
    "city": "Shiban"
}, {
    "id": 8,
    "country": "Portugal",
    "city": "Flor da Mata"
}, {
    "id": 9,
    "country": "Ireland",
    "city": "Tower"
}, {
    "id": 10,
    "country": "Indonesia",
    "city": "Paka"
}, {
    "id": 11,
    "country": "Uganda",
    "city": "Sembabule"
}, {
    "id": 12,
    "country": "Finland",
    "city": "Varkaus"
}, {
    "id": 13,
    "country": "China",
    "city": "Pingshan"
}, {
    "id": 14,
    "country": "China",
    "city": "Tangtuzhui"
}, {
    "id": 15,
    "country": "Mexico",
    "city": "Reforma"
}, {
    "id": 16,
    "country": "Poland",
    "city": "Mniszków"
}, {
    "id": 17,
    "country": "China",
    "city": "Huangge"
}, {
    "id": 18,
    "country": "Indonesia",
    "city": "Muara"
}, {
    "id": 19,
    "country": "Tajikistan",
    "city": "Qŭrghonteppa"
}, {
    "id": 20,
    "country": "Bolivia",
    "city": "San Juan del Surutú"
}, {
    "id": 21,
    "country": "Bhutan",
    "city": "Daga"
}, {
    "id": 22,
    "country": "Lithuania",
    "city": "Obeliai"
}, {
    "id": 23,
    "country": "Indonesia",
    "city": "Tulungrejo"
}, {
    "id": 24,
    "country": "Russia",
    "city": "Perovo"
}, {
    "id": 25,
    "country": "Vietnam",
    "city": "Lũng Hồ"
}, {
    "id": 26,
    "country": "Colombia",
    "city": "Ramiriquí"
}, {
    "id": 27,
    "country": "Portugal",
    "city": "Nogueira"
}, {
    "id": 28,
    "country": "Portugal",
    "city": "Azurva"
}, {
    "id": 29,
    "country": "Canada",
    "city": "Bedford"
}, {
    "id": 30,
    "country": "China",
    "city": "Xiamao"
}, {
    "id": 31,
    "country": "Thailand",
    "city": "Na Chaluai"
}, {
    "id": 32,
    "country": "Palestinian Territory",
    "city": "Za‘tarah"
}, {
    "id": 33,
    "country": "China",
    "city": "Yangzhuang"
}, {
    "id": 34,
    "country": "Pakistan",
    "city": "Wārāh"
}, {
    "id": 35,
    "country": "Philippines",
    "city": "Muricay"
}, {
    "id": 36,
    "country": "China",
    "city": "Baizhong"
}, {
    "id": 37,
    "country": "Poland",
    "city": "Nakło nad Notecią"
}, {
    "id": 38,
    "country": "Sweden",
    "city": "Södertälje"
}, {
    "id": 39,
    "country": "Indonesia",
    "city": "Badean"
}, {
    "id": 40,
    "country": "France",
    "city": "Challans"
}, {
    "id": 41,
    "country": "Sweden",
    "city": "Lidingö"
}, {
    "id": 42,
    "country": "Indonesia",
    "city": "Watuka"
}, {
    "id": 43,
    "country": "Philippines",
    "city": "Maagnas"
}, {
    "id": 44,
    "country": "China",
    "city": "Dongning"
}, {
    "id": 45,
    "country": "Kazakhstan",
    "city": "Zhangatas"
}, {
    "id": 46,
    "country": "Tanzania",
    "city": "Ndago"
}, {
    "id": 47,
    "country": "Malta",
    "city": "Imġarr"
}, {
    "id": 48,
    "country": "Greece",
    "city": "Nestório"
}, {
    "id": 49,
    "country": "Indonesia",
    "city": "Kudus"
}, {
    "id": 50,
    "country": "China",
    "city": "Tuchengzi"
}, {
    "id": 51,
    "country": "Colombia",
    "city": "Chimichagua"
}, {
    "id": 52,
    "country": "Philippines",
    "city": "Lapuz"
}, {
    "id": 53,
    "country": "Russia",
    "city": "Mayskiy"
}, {
    "id": 54,
    "country": "China",
    "city": "Huangqu"
}, {
    "id": 55,
    "country": "Botswana",
    "city": "Gobojango"
}, {
    "id": 56,
    "country": "China",
    "city": "Yengimahalla"
}, {
    "id": 57,
    "country": "Philippines",
    "city": "Cuevas"
}, {
    "id": 58,
    "country": "China",
    "city": "Xinjian"
}, {
    "id": 59,
    "country": "Bulgaria",
    "city": "Zavet"
}, {
    "id": 60,
    "country": "China",
    "city": "Dongba"
}, {
    "id": 61,
    "country": "Ethiopia",
    "city": "Dīla"
}, {
    "id": 62,
    "country": "Indonesia",
    "city": "Tangerang"
}, {
    "id": 63,
    "country": "Palestinian Territory",
    "city": "Wādī as Salqā"
}, {
    "id": 64,
    "country": "Japan",
    "city": "Ōkawara"
}, {
    "id": 65,
    "country": "Japan",
    "city": "Sawara"
}, {
    "id": 66,
    "country": "Portugal",
    "city": "Vermoim"
}, {
    "id": 67,
    "country": "Bangladesh",
    "city": "Sarankhola"
}, {
    "id": 68,
    "country": "Egypt",
    "city": "Sīdī Sālim"
}, {
    "id": 69,
    "country": "China",
    "city": "Zuolan"
}, {
    "id": 70,
    "country": "Portugal",
    "city": "Horta"
}, {
    "id": 71,
    "country": "China",
    "city": "Longkou"
}, {
    "id": 72,
    "country": "Sweden",
    "city": "Solna"
}, {
    "id": 73,
    "country": "Thailand",
    "city": "Bueng Sam Phan"
}, {
    "id": 74,
    "country": "France",
    "city": "Marseille"
}, {
    "id": 75,
    "country": "China",
    "city": "Lianyi"
}, {
    "id": 76,
    "country": "China",
    "city": "Gongqiao"
}, {
    "id": 77,
    "country": "Russia",
    "city": "Sorochinsk"
}, {
    "id": 78,
    "country": "Mexico",
    "city": "Buenos Aires"
}, {
    "id": 79,
    "country": "Belarus",
    "city": "Horad Smalyavichy"
}, {
    "id": 80,
    "country": "Egypt",
    "city": "Quţūr"
}, {
    "id": 81,
    "country": "Poland",
    "city": "Pszczew"
}, {
    "id": 82,
    "country": "United States",
    "city": "Toledo"
}, {
    "id": 83,
    "country": "Afghanistan",
    "city": "Andkhōy"
}, {
    "id": 84,
    "country": "Philippines",
    "city": "Tarlac City"
}, {
    "id": 85,
    "country": "Sweden",
    "city": "Stockholm"
}, {
    "id": 86,
    "country": "Indonesia",
    "city": "Sukasetia"
}, {
    "id": 87,
    "country": "Russia",
    "city": "Star’"
}, {
    "id": 88,
    "country": "Philippines",
    "city": "Little Baguio"
}, {
    "id": 89,
    "country": "Indonesia",
    "city": "Ponggeok"
}, {
    "id": 90,
    "country": "China",
    "city": "Shuanglong"
}, {
    "id": 91,
    "country": "China",
    "city": "Huyang"
}, {
    "id": 92,
    "country": "Brazil",
    "city": "Cruzeiro do Oeste"
}, {
    "id": 93,
    "country": "France",
    "city": "Nice"
}, {
    "id": 94,
    "country": "China",
    "city": "Zhenghu"
}, {
    "id": 95,
    "country": "Thailand",
    "city": "Bang Saphan"
}, {
    "id": 96,
    "country": "Palestinian Territory",
    "city": "Tarqūmyā"
}, {
    "id": 97,
    "country": "Brazil",
    "city": "Nova Era"
}, {
    "id": 98,
    "country": "Mexico",
    "city": "Vicente Guerrero"
}, {
    "id": 99,
    "country": "Japan",
    "city": "Tokorozawa"
}, {
    "id": 100,
    "country": "Argentina",
    "city": "Villa Santa Rosa"
}]

module.exports = data;